import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/navigation/nav";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";
import Footer from "@/components/Home/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={cn ("mx-auto", `${inter.className}`)}>
        <Providers>
          <Nav/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
